import type { Metadata } from "next";
import { Fira_Sans, Fira_Sans_Condensed, Lato, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const firaSansCondensed = Fira_Sans_Condensed({
  variable: "--font-fira-sans-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});


const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"]
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSansCondensed.variable} ${firaSans.variable} ${lato.variable} ${montserrat.variable} min-h-[100vh] antialiased`}
      >
        <div className="relative z-30 bg-bgcream" >
          <Header />
          {children}
        </div>
        <div className="w-full relative overflow-hidden z-0 h-[81vh]"></div>
        <div className="fixed z-0 h-[81vh] bottom-0 left-0 right-0">
          <Footer />
        </div>
      </body>
    </html>
  );
}
